### ISSUE TITLE
hold off on macOS 10.15.7 because accountsd is hogging CPU

### ISSUE THREAD

**Issue by maxheld83** [subugoe/metar#105]
this is an issue with my mac, though it appears to be widely affecting people with macs on 10.15.7, so I'm logging this here.

My mac has been unuseable since yesterday, with so far none of the fixes working.

Will report back here once I got something that works or once there is an reliable fix / documentation from apple.

best resource currently seems to be this: https://gist.github.com/l3nz/9fe151c0d398055b000d59b644f13c65

Good news: it's not just me, many people seem to be experiencing this bug.

**Comment by maxheld83** [comment]
Some more relevant resources:
- https://twitter.com/t0rst/status/1311236045988659201
- https://forums.macrumors.com/threads/accountsd-mail-process-and-cpu-usage.2212236/page-4?post=28964043#post-28964043
- https://twitter.com/lenz/status/1310219338901794817
- https://mrmacintosh.com/catalina-10-15-7-update-accountsd-using-400-if-using-icloud-mail/

Seems to be pretty widespread then and people are 😡.

**Comment by maxheld83** [comment]
this seems to have worked, for now:

```
sudo -v ; killall -9 accountsd com.apple.iCloudHelper ; defaults delete MobileMeAccounts ; 
mkdir ~/Library/Accounts/Backup; mv ~/Library/Accounts/*.sqlite* ~/Library/Accounts/Backup/ ; 
killall -9 accountsd com.apple.iCloudHelper ; sudo reboot
```

I would **not** recommend that unless you know what this does, and are able to set up things again as you like.

So I'm going to keep this open until there is an official fix.

**Comment by nicolacana** [comment]
Hi, after having done that I cannot resign again to iCloud: "An unexpected error occoured".
Now I am reinstalling Catalina on the first release installed on my mbp 16 with opt+cmd+shift+r.
Hope that it will fix it

**Comment by maxheld83** [comment]
this seems to have abated.
