### ISSUE TITLE
add teams for WAG and hybridoa on github

### ISSUE THREAD

**Issue by maxheld83** [subugoe/metaR#21]
The following people should be added to the [subugoe](http://github.com/subugoe) org and [WAG team](http://github.com/subugoe) on GitHub.
This will make it easier to collaborate, manage privileges and enforce security.

This is the subset of [WAG members](https://www.sub.uni-goettingen.de/kontakt/abteilungen-a-z/abteilungs-und-gruppendetails/abteilunggruppe/wissen-als-gemeingut/) who are already known to have/use GitHub; more may follow.

Checked entries [x] already are on the org and team.

- [x] @danielbangert [Daniel Bangert](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/daniel-bangert/)
- [x] @helenebr [Helene Brinken](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/helene-brinken/)
- [x] @mgottschling [Maxie Gottschling](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/maxie-gottschling/)
- [x] @maxheld83 [Maximilian Held](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/maximilian-cornelius-held/)
- [x] @Ahobert [Anne Hobert](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/anne-hobert/)
- [x] @jhoeffler [Jan Höffler](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/jan-h-hoeffler/)
- [x] @njahn82 [Najko Jahn](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/najko-jahn/)
- [ ] @gitti1 [Birgit Schmidt](https://www.sub.uni-goettingen.de/kontakt/personen-a-z/personendetails/person/birgit-schmidt/)
- [x] @Henrieke72 Henrieke Walter

**Comment by maxheld83** [comment]
the teams are there, but I need #20 to add everyone.

**Comment by njahn82** [comment]
can one of the exiting owners add the wag members to the team?

**Comment by maxheld83** [comment]
yes, I'm about to ask them along with a bunch of other things.

**Comment by maxheld83** [comment]
mostly done at least for those interested.
